### ISSUE TITLE
Load Playlist Images on Stop

### ISSUE THREAD

**Issue by pixelchutes** [jwplayer/jwplayer#1056]
I have been testing JW Player `v7.3.0-beta`, and have noticed some strange behavior with regards to poster / playlist image handling.

In an application built for `v7.2.4`, the image display works as you'd expect _(has worked this way since `v6.0`)_ -- but testing `v7.3.0`, I have found that the poster image only seems to be working if it's associated to the **first** item in a playlist.

Up to `7.2.4`, you could load a playlist, associate images with a given playlist item, and upon issuing `stop()` in `beforePlay` event, the correct image would be presented. Further, traditional handling would work, such as letting the video playback complete, etc.

In `v7.3.0-beta`, all you see is black :frowning: 

The only workaround I have found so far is reloading a solitary playlist, so that the playlist item / image in question is tied to the _first_ item in the playlist (index = 0). I would definitely consider this behavior a bug, hoping the internal JW Player team can confirm / fix before `7.3.0` hits stable.

### See working examples here:
* Plunker: [**7.3.0 bug**](https://plnkr.co/edit/wEofSgpDcCRe1QblQ2wP?p=preview)
* Plunker: [**7.2.4 functional**](https://plnkr.co/edit/YDc4FxTqB8ugdkvQyVJy?p=preview)

**Comment by robwalch** [comment]
We have a patch that hopefully addresses this. We made some changes to how posters are loaded and displayed based off of whether the playlist item has video or is audio only. We may not have thought of the 'stop' use case - always loading the current poster whenever the player switches to the idle state.

**Comment by pixelchutes** [comment]
Awesome news! I'd be happy to help test out as soon as staging/pre-release channel is updated with the aforementioned patch. Thanks Rob!

**Comment by robwalch** [comment]
Looked at it a little more. We're being quite aggressive about not loading the image now:
https://github.com/jwplayer/jwplayer/blob/master/src/js/view/preview.js

If we just update the background image on playlist item or idle as we used to it causes a lot of unnecessary network activity. Maybe we can avoid that using display: none. Another issue is that the state changes to idle in between playlist items so we're not able to tell if playback has stopped or we're just in between items.

**Comment by pixelchutes** [comment]
I'm guessing `oldstate` likely won't be able to answer the latter point. But, using `display: none` sounds promising without sacrificing any recent network performance gains.

**Comment by robwalch** [comment]
@pixelchutes please try with v7.3.1 http://ssl.p.jwpcdn.com/player/v/7.3.1/jwplayer.js

**Comment by pixelchutes** [comment]
@robwalch Unfortunately, this does **not** seem to be working...

`background-image` is not being set on `.jw-preview` unless playlist item index = 0, so the result is the same as the OP (just black)

![jw_7_playlist_image](https://cloud.githubusercontent.com/assets/352182/13225654/f6a47f2a-d94a-11e5-84ed-da98f219bf37.jpg)

**Comment by pixelchutes** [comment]
Can this issue be re-opened?

**Comment by robwalch** [comment]
The preview image is not set while video is playing. It should be set once the state changes to idle or complete.

**Comment by robwalch** [comment]
Can you provide steps to repro?

**Comment by pixelchutes** [comment]
@robwalch Yes, I already did. There are two links in the post above (under "See working examples here")

* Plunker: [**7.3.0 bug**](https://plnkr.co/edit/wEofSgpDcCRe1QblQ2wP?p=preview)
* Plunker: [**7.2.4 functional**](https://plnkr.co/edit/YDc4FxTqB8ugdkvQyVJy?p=preview)

NOTE: You'll need to update the license key

**Comment by robwalch** [comment]
Is there a reason you need to stop the player on 'beforePlay'? The fix only works if the item starts and then is stopped.

**Comment by pixelchutes** [comment]
Yes, because we are using native JWPlayer API for serving static image "stills" in between choreographed LIVE event / VOD footage, etc. The `.mp4` is a dummy placeholder, with the `stop()` allowing the poster image to render without error.

This is something we have always relied on, and has been done since `v4`, `v5`, `v6`, and up to `v7.2.4`.

**Comment by robwalch** [comment]
In your example the player goes into an "error" state because you're not providing valid urls. The changes to preview.js don't account for this state. Here's a PR #1063

**Comment by pixelchutes** [comment]
Beautiful! Thanks @robwalch -- Assuming all tests pass and this is merged, I'd be happy to test again and verify on my end once http://ssl.p.jwpcdn.com/player/v/7.3.1/jwplayer.js is updated.

**Comment by robwalch** [comment]
It may still not load the preview image is the playlist item changes, but stop is called while the state is still idle. If the state does not change, then the preview image will not be set. I think this is a valid change given the optimization we gain by not loading poster images that would never be shown with normal playback.

**Comment by pixelchutes** [comment]
Good to know. If I understand your last comment correctly, it sounds like this won't fully fix the issue in our current scenario, and currently there's no public method for loading just the preview image.

What we're hoping to avoid is being "forced" to render some kind of valid video/audio media _(e.g. 1 second black video or audio silence)_ **just** to leverage the built-in preview image handling. The player is otherwise perfectly capable of supporting the use case.

**Comment by robwalch** [comment]
If the content is invalid, the poster will load on error in 7.3.2. Posters always load when playing audio content. They also load before playback is started and when it's stopped after buffering or playback has bugun. Give a try:

http://ssl.p.jwpcdn.com/player/v/7.3.2/jwplayer.js

The only time posters might not load is if you autostart, or go to a playlist item and but stop playback before the player has a chance to attempt to load the item which could still be the case on beforePlay with some providers.

**Comment by pixelchutes** [comment]
Understood, confirmed just now `7.3.2` does not work for us in that case _(that's what I was afraid of, exactly how we were relying on preview image rendering.)_

**Comment by pixelchutes** [comment]
@robwalch FYI, still trying to confirm exactly, but this may not work as intended when `primary: 'flash'`

**Comment by robwalch** [comment]
Showing the poster for audio files depends on a mediaType event being sent from the provider. These should be sent from flash.js but it may be a timing issue where it fires before the playlistItem event on load.

**Comment by robwalch** [comment]
Reopening until we can handle your use case with Flash and stopping onBeforePlay. I still want the background cleared when video is playing. The challenge with adding the posters on 'stop' is that can be called in-between playback, so we want to either defer the loading just a bit or be able to determine that stop was called externally.

**Comment by pixelchutes** [comment]
Good call, Rob. For now, we've been able to work with the efforts put into `7.3.2` by switching our primary mode to `html5` _(better anyway)_, and conditionally hiding controls for posters via `setControls(false)`.

**Comment by fdambrosio** [comment]
Hi, 
I've verified that with 7.3.4 and audio stream (html5+dash) there is this problem: after "play" it shows a black screen without image that doesn't stay visible. I've tested with Chrome on Mac. 

example: http://www.fdambrosio.net/test/player7/audio.html

Best regards

**Comment by pixelchutes** [comment]
@fdambrosio the poster image in your example is throwing a 404 error:
> http://web-0.radioradicale.it/sites/all/themes/radioradicale_2014/images/audio-400.png

**Comment by fdambrosio** [comment]
@pixelchutes sorry, now I've updated the page with working url 
http://www.fdambrosio.net/test/player7/audio.html

**Comment by dannyfinks** [comment]
Hi @pixelchutes seems their are some issues with that playlist setup would you be able to modify your playlist block to look like below. Also there is an image property being provided below the playlist.
```
"playlist":
            [{
                "sources": [
                    {"file": "http://audio-aac.radioradicale.it:1935/aac-1/_definst_/2016/03/11/MP824455.m4a/playlist.m3u8"}
                ],
                tracks: [{ file: 'webvtt.vtt'}],
                "image": "http://www.radioradicale.it/sites/all/themes/radioradicale_2014/images/audio-400.png"
            }, {
                "sources": [
                    {"file": "http://audio-aac.radioradicale.it:1935/aac-1/_definst_/2016/03/11/MP824455.m4a/playlist.m3u8"}
                ],
                tracks: [{ file: 'webvtt.vtt'}],
                "image": "http://www.radioradicale.it/sites/all/themes/radioradicale_2014/images/audio-400.png"
            }],
```

**Comment by pixelchutes** [comment]
@dannyfinks you would need to ask @fdambrosio :smile:

**Comment by fdambrosio** [comment]
@dannyfinks @pixelchutes thanks! :-) now poster image works when I use hls stream (we'll have multiple sources for playlists), but If I have an audio stream with mpeg-dash the poster image doesn't show.
Now I'm unable to show a working page because the dash streaming server isn't available worldwide, but the cose is like this: 

```
playlist:
[{ sources: [ 
{ file:'http://audio-aac.radioradicale.it:1935/aac-1/_definst_/2016/03/11/MP824455.m4a/manifest.mpd',
tracks: [{ file: 'webvtt.vtt'}],
},
{  file:'http://audio-aac.radioradicale.it:1935/aac-1/_definst_/2016/03/11/MP824455.m4a/playlist.m3u8',
tracks: [{ file: 'webvtt.vtt'}],
}],
image: 'http://www.radioradicale.it/sites/all/themes/radioradicale_2014/images/audio-400.png',
}]
```

**Comment by fdambrosio** [comment]
Now you can see here with working m4a/dash-hls streaming. 
http://www.fdambrosio.net/test/player7/audio.html

When the file is playing the poster image is black. on Chrome (using dash) but it's correct if you use Safari (hls)

Francesco

**Comment by fdambrosio** [comment]
Hello, there's news about this bug?

**Comment by robwalch** [comment]
I don't think we have a fix for the shaka provider in 7.4.0-beta.1. We'll circle back before release in mid April.

**Comment by fdambrosio** [comment]
@robwalch Hi, there's news with 7.4-RC?

**Comment by waxidiotic** [comment]
Hi, @fdambrosio. The first release candidate of 7.4 was released on Friday (4/15). Please see [our developer site](https://developer.jwplayer.com/jw-player/docs/developer-guide/release_notes/release_notes_7/) for more information.

**Comment by fdambrosio** [comment]
thanks @waxidiotic but If I'm unable to build 7.4-RC, in the list I see that there's not fix about poster audio image for dash, also if shaka provider is updated. I hope that this will be fixed soon.

**Comment by robwalch** [comment]
@fdambrosio We deployed v7.4.0-rc.2 to our CDN last night. Can you update your test page to use this path //ssl.p.jwpcdn.com/player/v/7.4.0-rc.2/jwplayer.js ?

While we've made some updates to shaka, I'm not sure that we've sorted out the detection of audio only streams for DASH in shaka. Updating your test would help with this.

Thanks!

**Comment by fdambrosio** [comment]
@robwalch thanks, I've updated test page with 7.4.0-rc.2 here http://www.fdambrosio.net/test/player7/audio.html but the problem is still here: poster image doesn't work for audio & dash. Only with HLS poster image works. 
UPDATE VTT AUDIO: there's another issue with subtitles .vtt that doesn't work with audio dash/hls if I use multiple sources&playlist. In test audio page vtt track doesn't works: http://www.fdambrosio.net/test/player7/audio.html 
The same vtt file works with video page test here: http://www.fdambrosio.net/test/player7/index.html

**Comment by fdambrosio** [comment]
@robwalch there's a workaround while we wait the fix in 7.5?!?

**Comment by waxidiotic** [comment]
@fdambrosio - @robwalch may have a better workaround but i've told people in the past that one would be to have the player in "audio-only" mode (when the height is set to 40px) so it's just the control bar and have it directly below your poster image on the page. to the viewer, it would look just like it would if the poster image was playing in the player.

**Comment by robwalch** [comment]
I'll see if we can fix the issue and cherrypick it into an upcoming patch.

For now this can easily be worked around in 7.4.0 with a little CSS. This example always shows the preview and puts the captions on top of the preview, only in your `#radioplayer`:

```css
#radioplayer .jw-preview {
    display: block;
}
#radioplayer .jw-captions {
    z-index: 1;
}
```

Once the mediaType is set correctly, the display and DOM placement of the preview will be updated for you. We never use z-index in the player to avoid collision with page styles.

**Comment by fdambrosio** [comment]
thanks @robwalch ! 
note: this workaround works only if there isn't autostart. 

@waxidiotic we have both video and audio and this is some reasons to have big audio player: 
- have the same  player dimension and experience on all site
- we could have video and audio mixed in the same playlist
- webvtt subtitles for audio like for videos

**Comment by johnBartos** [comment]
I believe a fix made its way into 7.4.3. Can you confirm before I close?

**Comment by robwalch** [comment]
Reading through the thread there are several issues here. The overall need is to have universal support for displaying posters, both when the player has stopped, and when playing audio-only media, in any media provider.

1. @pixelchutes reported a regression made in this project which was addressed for most cases...
2. ...except where Flash is playing back audio only media without dispatching a media-type event. I don't see any updates indicating that that has been addressed, or confirmation is that was also a recent regression.
3. @fdambrosio added that posters were not being displayed with DASH audio-only streams. The focus of this thread has since shifted to that issue. That issue is fixed in 7.4.3. However, the poster is hidden while media is buffering...

With that said, I'm going to close this topic. Feel free to open new a new issue with any problems found in 7.4.3.
