### ISSUE TITLE
No buffering icon on HTML5 HLS version when seeking

### ISSUE THREAD

**Issue by konradpietrzkiewicz** [jwplayer/jwplayer#1265]
### Expected Behavior

When seeking within video buffering icon should be shown - the same as on flash version.
### Actual Behavior

On HTML5 HLS provider when player buffers video the loading icon is not displayed. 
### Steps to reproduce
1. go to http://demo.jwplayer.com/stream-tester/
2. load example stream
3. after video is played seek to the middle of video - no buffer icon is shown like on flash version
### Environment
- PC
- Windows 10
-  7.4.4 (http://demo.jwplayer.com/stream-tester/)

**Comment by johnBartos** [comment]
Hey @konradpietrzkiewicz, thanks for the report! I was able to reproduce it so it looks like a bug to me.

**Comment by fdambrosio** [comment]
Hi, 
this bug will be fixed with 7.5?

**Comment by konradpietrzkiewicz** [comment]
I've checked it few days ago and it was still there

**Comment by fdambrosio** [comment]
I've tested 7.5.0 RC-1 and bug is still here

**Comment by johnBartos** [comment]
Hey guys, we're aware of this but it'll be fixed in 7.6

**Comment by fdambrosio** [comment]
Hi, 
I'm testing 7.6.0 and this bug is still here, why?

**Comment by doctorcoder** [comment]
I've tested 7.6.1 and the bug is still there. It's been more than two months. Any updates on when will it be fixed?

**Comment by johnBartos** [comment]
@doctorcoder We've been quite busy with features, I've taken note of this and I'll bring it up again

**Comment by doctorcoder** [comment]
@johnBartos I saw 7.7 came out. Has this bug been fixed in that?

**Comment by doctorcoder** [comment]
Hi @johnBartos I just tested the 7.7.0-rc.1 in html5 and I guess the bug is still there. Any idea if you will be fixing it in this version?

**Comment by fdambrosio** [comment]
Hi, 
there's bug on 7.7.0-rc.2 too

**Comment by fdambrosio** [comment]
Hi, news?

**Comment by fdambrosio** [comment]
up

**Comment by konradpietrzkiewicz** [comment]
this was fixed in version 7.8.2 (from relase notes):

Seeking outside the buffer in an HLS stream now properly updates the state to buffering.

tested also on 7.12 and its working fine

**Comment by shyamchandranmec** [comment]
Hi, I checked on version 7.12.8. Its not working.
