### ISSUE TITLE
Live DVR stream plays from start of playlist, not at live point.

### ISSUE THREAD

**Issue by chrisgerrish** [jwplayer/jwplayer#1723]
### Expected Behavior

When playing a live DVR stream, the stream should start at the live point of the stream

### Actual Behavior

When playing a live DVR stream, the stream begins to play at the start of the DVR playlist, not at the end or live point.  You can hit the live button, and it will jump to the live point of the stream.

### Steps to reproduce

1. M3U8 to test: https://0ImJlo1-lh.akamaihd.net/i/chrisdvr_1@193520/master.m3u8
2. When stream plays, it will play from the start of the DVR window.

I will stream this live for the next 2 hours today, and can stream again tomorrow afternoon.  After the stream has been stopped, the DVR plays like it should from the start. 

### Environment

- *Macbook Pro*
- *OSX | 10.12.2*
- *Chrome | 55.0.2883.95*
- *JW Player 7.9.beta2*

**Comment by johnBartos** [comment]
@chrisgerrish Recently this was a bug but I thought I fixed it in 7.8.7, next time I'm free I'll ping you for the stream

**Comment by chrisgerrish** [comment]
@johnBartos sounds good

**Comment by chrisgerrish** [comment]
@johnBartos I have a stream running right now at the same address if you want to test.  Seems to be an issue still in 7.9.  The player now looks to be trying to download all the chunks in the playlist and then it will start playing from the beginning.

**Comment by johnBartos** [comment]
@chrisgerrish There's a fix for this landing in 7.10

https://github.com/jwplayer/hls.js/pull/59

**Comment by chrisgerrish** [comment]
Thanks, the release notes mentioned it had been fixed in 7.9 so I was just checking in.

**Comment by johnBartos** [comment]
> The player now looks to be trying to download all the chunks in the playlist and then it will start playing from the beginning

A fix for this is landing in 7.10. I believe this is the cause of streams not starting at the live edge - I'll bug someone about updating the notes.

In the meantime you can fix this issue yourself by ensuring that each segment in your stream starts with keyframes. Closing this out since I can confirm the fix.

**Comment by chrisgerrish** [comment]
For what its worth, I am using Wirecast as an encoder for this test stream.  I inspected the first frames of the first two segments of the playlist and they both had keyframes from what I could tell.

https://0imjlo1-lh.akamaihd.net/i/chrisdvr_1@193520/segment8683688_400_av-p.ts?sd=10
https://0imjlo1-lh.akamaihd.net/i/chrisdvr_1@193520/segment8683689_400_av-p.ts?sd=10

`[FRAME]
media_type=video
stream_index=0
key_frame=1
pkt_pts=7067796822
pkt_pts_time=78531.075800
pkt_dts=7067796822
pkt_dts_time=78531.075800
best_effort_timestamp=7067796822
best_effort_timestamp_time=78531.075800
pkt_duration=N/A
pkt_duration_time=N/A
pkt_pos=22560
pkt_size=27800
width=426
height=240
pix_fmt=yuv420p
sample_aspect_ratio=1:1
pict_type=I
coded_picture_number=12
display_picture_number=0
interlaced_frame=0
top_field_first=0
repeat_pict=0
[/FRAME]`

**Comment by johnBartos** [comment]
@chrisgerrish The bug happens when segments do not start with a keyframe, resulting in dropped frames. We have a feature in our hls library which seeks backwards to find the keyframe so it can decode the b-frames. If no segments start with a keyframe, it seeks back to the start (downloading each segment in reverse order along the way).

**Comment by chrisgerrish** [comment]
@johnBartos Sorry, not trying to beat a dead horse here, but I was able to verify that the segments started with a keyframe.  My last post was an output of ffprobe, and that was the first frame of the ts segment showing it was a keyframe `key_frame=1`, and also showing `pict_type=I`.  The next frame shows `key_frame=0` and `pict_type=P`.
