### ISSUE TITLE
SetCurrentAudioTrack doesn't deselect the previous in the UI

### ISSUE THREAD

**Issue by andreasgan** [jwplayer/jwplayer#3685]
### Expected Behavior

When programatically changing current audio track through setCurrentAudioTrack(index) the current audio track should be the only "selected" audio track in the UI.

### Actual Behavior

After doing setCurrentAudioTrack(index) the previous audio track is still selected in the UI, which makes it unclickable. One has to select another audio track to clear it. The audio is fine.
![image](https://user-images.githubusercontent.com/727125/83119277-cf035d00-a0cf-11ea-9a1c-0e79fbcdbd3e.png)

### Steps to reproduce

1. Have a video with multiple audio tracks, like this demo: https://www.jwplayer.com/developers/web-player-demos/hlsv4-audio-tracks/
2. Run ```jwplayer().setCurrentAudioTrack(1)```
3. Look at the audio tracks

### Environment

- Google Chrome | Version 81.0.4044.138 (Official Build) (64-bit)
- 8.14.0 | https://cdn.jwplayer.com/libraries/wr6i4gal.js

**Comment by andreasgan** [comment]
Looks like this was fixed in 8.15.
Thanks!

**Comment by andreasgan** [comment]
The bug is back in version 15.2 😶

**Comment by weokap** [comment]
Version 8.16 and the bug still there. Any plan to fix this soon?

**Comment by andreasgan** [comment]
Jwplatform support responded with this after a while: "Due to the current workload of higher priority tasks we are unable to provide an ETA for a fix for this issue. It is currently set to be fixed in one of the 8.17.x versions, however, these won't be released in the foreseeable future."

**Comment by robwalch** [comment]
This is fixed in 8.17.0, along with the audio track menu and `getAudioTracks()` not refreshing between items.

https://releases.jwplayer.com/jw-player/#v8.17.0
